// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Ostap00034/course-work-backend/auth-service/ent/schema"
	"github.com/Ostap00034/course-work-backend/auth-service/ent/token"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescIssuedAt is the schema descriptor for issued_at field.
	tokenDescIssuedAt := tokenFields[3].Descriptor()
	// token.DefaultIssuedAt holds the default value on creation for the issued_at field.
	token.DefaultIssuedAt = tokenDescIssuedAt.Default.(func() time.Time)
	// tokenDescRevoked is the schema descriptor for revoked field.
	tokenDescRevoked := tokenFields[5].Descriptor()
	// token.DefaultRevoked holds the default value on creation for the revoked field.
	token.DefaultRevoked = tokenDescRevoked.Default.(bool)
	// tokenDescID is the schema descriptor for id field.
	tokenDescID := tokenFields[0].Descriptor()
	// token.DefaultID holds the default value on creation for the id field.
	token.DefaultID = tokenDescID.Default.(func() uuid.UUID)
}
