// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Ostap00034/course-work-backend-auth-service/ent/predicate"
	"github.com/Ostap00034/course-work-backend-auth-service/ent/token"
	"github.com/google/uuid"
)

// TokenUpdate is the builder for updating Token entities.
type TokenUpdate struct {
	config
	hooks    []Hook
	mutation *TokenMutation
}

// Where appends a list predicates to the TokenUpdate builder.
func (tu *TokenUpdate) Where(ps ...predicate.Token) *TokenUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUserID sets the "user_id" field.
func (tu *TokenUpdate) SetUserID(u uuid.UUID) *TokenUpdate {
	tu.mutation.SetUserID(u)
	return tu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableUserID(u *uuid.UUID) *TokenUpdate {
	if u != nil {
		tu.SetUserID(*u)
	}
	return tu
}

// SetToken sets the "token" field.
func (tu *TokenUpdate) SetToken(s string) *TokenUpdate {
	tu.mutation.SetToken(s)
	return tu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableToken(s *string) *TokenUpdate {
	if s != nil {
		tu.SetToken(*s)
	}
	return tu
}

// SetIssuedAt sets the "issued_at" field.
func (tu *TokenUpdate) SetIssuedAt(t time.Time) *TokenUpdate {
	tu.mutation.SetIssuedAt(t)
	return tu
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableIssuedAt(t *time.Time) *TokenUpdate {
	if t != nil {
		tu.SetIssuedAt(*t)
	}
	return tu
}

// SetExpiresAt sets the "expires_at" field.
func (tu *TokenUpdate) SetExpiresAt(t time.Time) *TokenUpdate {
	tu.mutation.SetExpiresAt(t)
	return tu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableExpiresAt(t *time.Time) *TokenUpdate {
	if t != nil {
		tu.SetExpiresAt(*t)
	}
	return tu
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (tu *TokenUpdate) ClearExpiresAt() *TokenUpdate {
	tu.mutation.ClearExpiresAt()
	return tu
}

// SetRevoked sets the "revoked" field.
func (tu *TokenUpdate) SetRevoked(b bool) *TokenUpdate {
	tu.mutation.SetRevoked(b)
	return tu
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableRevoked(b *bool) *TokenUpdate {
	if b != nil {
		tu.SetRevoked(*b)
	}
	return tu
}

// Mutation returns the TokenMutation object of the builder.
func (tu *TokenUpdate) Mutation() *TokenMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TokenUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TokenUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TokenUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UserID(); ok {
		_spec.SetField(token.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := tu.mutation.Token(); ok {
		_spec.SetField(token.FieldToken, field.TypeString, value)
	}
	if value, ok := tu.mutation.IssuedAt(); ok {
		_spec.SetField(token.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.ExpiresAt(); ok {
		_spec.SetField(token.FieldExpiresAt, field.TypeTime, value)
	}
	if tu.mutation.ExpiresAtCleared() {
		_spec.ClearField(token.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := tu.mutation.Revoked(); ok {
		_spec.SetField(token.FieldRevoked, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TokenUpdateOne is the builder for updating a single Token entity.
type TokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenMutation
}

// SetUserID sets the "user_id" field.
func (tuo *TokenUpdateOne) SetUserID(u uuid.UUID) *TokenUpdateOne {
	tuo.mutation.SetUserID(u)
	return tuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableUserID(u *uuid.UUID) *TokenUpdateOne {
	if u != nil {
		tuo.SetUserID(*u)
	}
	return tuo
}

// SetToken sets the "token" field.
func (tuo *TokenUpdateOne) SetToken(s string) *TokenUpdateOne {
	tuo.mutation.SetToken(s)
	return tuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableToken(s *string) *TokenUpdateOne {
	if s != nil {
		tuo.SetToken(*s)
	}
	return tuo
}

// SetIssuedAt sets the "issued_at" field.
func (tuo *TokenUpdateOne) SetIssuedAt(t time.Time) *TokenUpdateOne {
	tuo.mutation.SetIssuedAt(t)
	return tuo
}

// SetNillableIssuedAt sets the "issued_at" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableIssuedAt(t *time.Time) *TokenUpdateOne {
	if t != nil {
		tuo.SetIssuedAt(*t)
	}
	return tuo
}

// SetExpiresAt sets the "expires_at" field.
func (tuo *TokenUpdateOne) SetExpiresAt(t time.Time) *TokenUpdateOne {
	tuo.mutation.SetExpiresAt(t)
	return tuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableExpiresAt(t *time.Time) *TokenUpdateOne {
	if t != nil {
		tuo.SetExpiresAt(*t)
	}
	return tuo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (tuo *TokenUpdateOne) ClearExpiresAt() *TokenUpdateOne {
	tuo.mutation.ClearExpiresAt()
	return tuo
}

// SetRevoked sets the "revoked" field.
func (tuo *TokenUpdateOne) SetRevoked(b bool) *TokenUpdateOne {
	tuo.mutation.SetRevoked(b)
	return tuo
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableRevoked(b *bool) *TokenUpdateOne {
	if b != nil {
		tuo.SetRevoked(*b)
	}
	return tuo
}

// Mutation returns the TokenMutation object of the builder.
func (tuo *TokenUpdateOne) Mutation() *TokenMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TokenUpdate builder.
func (tuo *TokenUpdateOne) Where(ps ...predicate.Token) *TokenUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TokenUpdateOne) Select(field string, fields ...string) *TokenUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Token entity.
func (tuo *TokenUpdateOne) Save(ctx context.Context) (*Token, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TokenUpdateOne) SaveX(ctx context.Context) *Token {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TokenUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TokenUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TokenUpdateOne) sqlSave(ctx context.Context) (_node *Token, err error) {
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Token.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, token.FieldID)
		for _, f := range fields {
			if !token.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != token.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UserID(); ok {
		_spec.SetField(token.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := tuo.mutation.Token(); ok {
		_spec.SetField(token.FieldToken, field.TypeString, value)
	}
	if value, ok := tuo.mutation.IssuedAt(); ok {
		_spec.SetField(token.FieldIssuedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.ExpiresAt(); ok {
		_spec.SetField(token.FieldExpiresAt, field.TypeTime, value)
	}
	if tuo.mutation.ExpiresAtCleared() {
		_spec.ClearField(token.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := tuo.mutation.Revoked(); ok {
		_spec.SetField(token.FieldRevoked, field.TypeBool, value)
	}
	_node = &Token{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
